# docker-compose.yml
services:
  eureka-server:
    container_name: eureka-server
    restart: always
    build: ./eureka-server
    ports:
      - "8761:8761"

  order-service:
    container_name: order-service
    restart: always
    build: ./order-service
    depends_on:
      - eureka-server
      - kafka
      - zookeeper
      - postgres
    links:
      - kafka
      - eureka-server
      - postgres

  payment-service:
    container_name: payment-service
    restart: always
    build: ./payment-service
    depends_on:
      - eureka-server
      - kafka
      - zookeeper
      - postgres
    links:
      - kafka
      - eureka-server
      - postgres

  restaurant-service:
    container_name: restaurant-service
    restart: always
    build: ./restaurant-service
    depends_on:
      - eureka-server
      - kafka
      - zookeeper
      - postgres
    links:
      - kafka
      - eureka-server
      - postgres

  delivery-service:
    container_name: delivery-service
    restart: always
    build: ./delivery-service
    depends_on:
      - eureka-server
      - kafka
      - zookeeper
      - postgres
    links:
      - kafka
      - eureka-server
      - postgres

  api-gateway:
    container_name: api-gateway
    restart: always
    build: ./api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
      - order-service
      - payment-service
      - restaurant-service
      - delivery-service
      - kafka
    links:
      - eureka-server
      - order-service
      - payment-service


  zookeeper:
    container_name: zookeeper
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka:
    container_name: kafka
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9091,EXTERNAL://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

    postgres:
      container_name: postgres
      restart: always
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

volumes:
  zookeeper-volume:
  kafka-volume: