server:
  port: 8765

#Id server
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowercase-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
            - Method=GET, POST, DELETE
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/account/**
            - Method=GET, POST
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/products/**
            - Method=GET

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss.SSS} - %msg%n"
