server:
  port: 8761

#Id server
spring:
  application:
    name: eserver

#Eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss.SSS} - %msg%n"
