server:
  port: 0

#Id server
spring:

  application:
    name: delivery-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: postgresql://postgres:postgres@postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9091

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss.SSS} - %msg%n"
  level:
    root: warn
